/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as TriggersIndexImport } from './routes/triggers/index'
import { Route as TriggersTriggerIdImport } from './routes/triggers/$triggerId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TriggersIndexRoute = TriggersIndexImport.update({
  id: '/triggers/',
  path: '/triggers/',
  getParentRoute: () => rootRoute,
} as any)

const TriggersTriggerIdRoute = TriggersTriggerIdImport.update({
  id: '/triggers/$triggerId',
  path: '/triggers/$triggerId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/triggers/$triggerId': {
      id: '/triggers/$triggerId'
      path: '/triggers/$triggerId'
      fullPath: '/triggers/$triggerId'
      preLoaderRoute: typeof TriggersTriggerIdImport
      parentRoute: typeof rootRoute
    }
    '/triggers/': {
      id: '/triggers/'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof TriggersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signup': typeof SignupRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers': typeof TriggersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signup': typeof SignupRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers': typeof TriggersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signup': typeof SignupRoute
  '/triggers/$triggerId': typeof TriggersTriggerIdRoute
  '/triggers/': typeof TriggersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signup'
    | '/triggers/$triggerId'
    | '/triggers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/signup' | '/triggers/$triggerId' | '/triggers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signup'
    | '/triggers/$triggerId'
    | '/triggers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignupRoute: typeof SignupRoute
  TriggersTriggerIdRoute: typeof TriggersTriggerIdRoute
  TriggersIndexRoute: typeof TriggersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignupRoute: SignupRoute,
  TriggersTriggerIdRoute: TriggersTriggerIdRoute,
  TriggersIndexRoute: TriggersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/signup",
        "/triggers/$triggerId",
        "/triggers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/triggers/$triggerId": {
      "filePath": "triggers/$triggerId.tsx"
    },
    "/triggers/": {
      "filePath": "triggers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
